FROM python:3.9.7

#start python virtual environment
RUN python3 -m venv /opt/venv

#get dependencies
COPY requirements.txt .
RUN . /opt/venv/bin/activate && pip install -r requirements.txt

#run file
COPY app.py .
CMD . /opt/venv/bin/activate && exec python app.py
